## Introduction 

Linear algebra is essential in multiple areas of science. Since linear equations are easy to solve, modern science, including mathematics, physics and engineering contains models of linear equations. For example, In physics, linear algebra can be applied to solve Maxwell’s equations. In data science, we use linear regression to predict the result on a large set of training data. This tutorial will introduce a powerful library SciPy, which provides key functions to utilize linear algebra. 

As an extension of NumPy, SciPy provides mathematical algorithms and high-level data processing routines, including optimization, regression, etc. With SciPy, users can easily manipulate data with high-level commands.

For more details, please refer to the link: http://www.scipy.org/scipylib/index.html

## Tutorial Content

The tutorial will cover:

* [Installing SciPy library](#Installing-SciPy-library)
* [Matrix and Array in NumPy](#Matrix-and-Array-in-NumPy) 
* [Basic Operations on Matrix](#Basic-Operations-on-Matrix):
    * [Finding Inverse](#Finding-Inverse)
    * [Finding Transpose](#Finding-Transpose)
    * [Finding Determinant](#Finding-Determinant)
    * [Finding Trace](#Finding-Trace)
    * [Finding Eigenvalues and Eigenvectors](#Finding-Eigenvalues-and-Eigenvectors)
* [Solving Linear Equations](#Solving-Linear-Equations)
* [LU Decomposition](#LU-Decomposition)
* [Applications in Economics](#Applications-in-Economics) 
    * [Unemployment Rate](#Unemployment-Rate)
    * [Input-output Model](#Input-output-Model)
* [Sparse Linear Algebra](#Sparse-Linear-Algebra)
* [Summary and Reference](#Summary-and-Reference)
    
        

## Installing SciPy library

It is easier to install SciPy by downloading one of the following Python distributions, which includes all the essential packages:

For Linux, Windows and Mac users:
* [Anaconda](https://www.continuum.io/downloads): A free distribution for the SciPy stack. 
* [Enthought Canopy](https://www.enthought.com/products/canopy/): The free and commercial versions include the core SciPy stack packages. 
* [Pyzo](http://www.pyzo.org/): A free distribution based on Anaconda and the IEP interactive development environment. 

For Windows users:
* [Python(x,y)](http://python-xy.github.io/): A free distribution including the SciPy stack, based around the Spyder IDE. 
* [WinPython](http://winpython.github.io/): A free distribution including the SciPy stack. 

After installing SciPy, make sure the following commands work for you:

In [2]:
import scipy as sp
import numpy as np

## Matrix and Array in NumPy

Before digging into linear algebra applications, we need to know the data type for operations: numpy.matrix and numpy.ndarray.

Although numpy.matrix has some advantages: it supports MATLAB-like creation syntax and has shortcuts for matrix multiplication, inverse and transpose, it is not recommended to use due to unexpected issues. In this tutorial, we will keep both numpy.matrix and numpy.array, but we recommend using numpy.array to save you from headaches.

Create a matrix and an array by NumPy:

In [3]:
# create numpy matrix
A = np.mat([[1, 2], [3, 4]])
print A

# Matlab-like creation syntax
B = np.mat('[1 2; 3 4]')
print B

# create numpy array
C = np.array([[1,2],[3,4]])
print C

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


## Basic Operations on Matrix
### Finding Inverse

The inverse of a square matrix $A$ is a matrix $A^{-1}$ such that 

$$AA^{-1} = I$$ 

where $I$ is the identity matrix. 

The inverse of a matrix can be obtained by $A.I$ for a NumPy matrix $A$ and scipy.linalg.inv($B$) for a Numpy array $B$.

In [ ]:
# find inverse (values should be the same)
from scipy import linalg
# matrix
A = np.mat([[1, 2], [3, 4]])

# array
B = np.array([[1, 2], [3, 4]])

# inverse of a matrix
A_inverse = A.I

# inverse of an array
B_inverse = linalg.inv(B)

print A_inverse # should be the same as
print B_inverse

print A.dot(A_inverse) # check the matrix should be I
print B.dot(B_inverse) # check the matrix should be I

### Finding Transpose
The transpose of a matrix $A$ is a matrix $A^{T}$.

The $i^{th}$ row, $j^{th}$ column element of $A^{T}$ is the $j^{th}$ row, $i^{th}$ column element of $A$: 

$$A_{ij}^{T} = A_{ji}$$

The transpose of a matrix is computed by $A.T$ for a NumPy matrix $A$ and $B.T$ or numpy.transpose($B$) for a NumPy array $B$.

In [5]:
# matrix
A = np.mat([[1, 2], [3, 4]])

# array
B = np.array([[1, 2], [3, 4]])

# transpose of a matrix
A_trans = A.T
print A_trans

# transpose of an array
B_trans = np.transpose(B)
print B_trans
# or
B_trans = B.T
print B_trans

[[1 3]
 [2 4]]
[[1 3]
 [2 4]]
[[1 3]
 [2 4]]


### Finding Determinant

The determinant of a square matrix $A$ is $|A|$, which can be viewed as the scaling factor of the transformation.

The determinant of a NumPy array or matrix is obtained by scipy.linalg.det().

In [ ]:
# matrix
A = np.mat([[1, 2], [3, 4]])

# array
B = np.array([[1, 2], [3, 4]])

# get the determinant of a matrix
A_det = linalg.det(A)

# get the determinant of an array
B_det = linalg.det(B)

print A_det
print B_det

### Finding Trace
The trace of a $n \times n$ square matrix $A$ is the sum of the elements on the main diagonal of A. 

$$tr(A) = a_{11} + a_{22} + .... + a_{nn} = \sum_{i=1}^n a_{ii}$$

The trace of a NumPy array or matrix is obtained by using the numpy.trace().

In [ ]:
# matrix
A = np.mat([[1, 2], [3, 4]])

# array
B = np.array([[1, 2], [3, 4]])

#get the trace of a matrix
A_trace = np.trace(A)

#get the trace of an array
B_trace = np.trace(B)

print A_trace
print B_trace

### Finding Eigenvalues and Eigenvectors

The eigenvalue-eigenvector problem is defined by

$$Av = λv$$
where $A$ is a square matrix, $λ$ is a scalar and $v$ is a vector.

An $n \times n$ square matrix has $n$ eigenvalues, which can be found by

$$|A−λI| = 0$$

Each eigenvalue corresponds to an eigenvector. 

The eigenvalues and eigenvectors of a square matrix can be obtained by scipy.linalg.eig()

In [ ]:
# matrix
A = np.mat([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# array
B = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

lamda, v = linalg.eig(A)
print lamda   # eigenvalues
print v # eigenvectors
lamda_, v_ = linalg.eig(B)
print lamda_ # eigenvalues
print v_ # eigenvectors

# We can find each eigenvector by
print v[:, 0]   # first eigenvector
print v[:, 1]   # second eigenvector
print v[:, 2]   # third eigenvector
print np.sum(abs(v**2), axis=0)  # check eigenvectors are unitary

## Solving Linear Equations
In a linear system, we have linear algebraic equations:

\begin{equation*}
a_1 x + b_1 y + c_1 z = d_1
\end{equation*}
\begin{equation*}
a_2 x + b_2 y + c_2 z = d_2
\end{equation*}
\begin{equation*}
a_3 x + b_3 y + c_3 z = d_3
\end{equation*}

which can be written in matrix form:

\begin{equation*}
\begin{bmatrix}
a_1 & b_1 & c_1 \\
a_2 & b_2 & c_2 \\
a_3 & b_3 & c_3
\end{bmatrix}
\begin{bmatrix}
x \\
y \\
z
\end{bmatrix}
=
\begin{bmatrix}
d_1 \\
d_2 \\
d_3
\end{bmatrix}
\end{equation*}

or $$Cv = d$$

where $C$ is the coefficient matrix, $v$ and $d$ are vectors.

Note that the coefficient matrix must be nonsingular; otherwise, it has a determinant of zero.

The linear equations can be solved by scipy.linalg.solve(), which is faster and more stable than computing the inverse then dot the right-hand side vector:
$$v = C^{-1}d$$

In [ ]:
# coefficient matrix
C = np.array([[6, -2, 3], [2, -7, 5], [-3, 4, 0]])

# right-hand side vector
d = np.array([4, 0, -5])

sol = linalg.inv(C).dot(d)  # slow
print sol
print C.dot(sol) - d  # check the vector should be all 0s

sol = linalg.solve(C, d) # fast and stable
print sol
print C.dot(sol) - d  # check the vector should be all 0s

## LU Decomposition

We can decompose the coefficient matrix $C$ by LU decomposition if the right-hand side vector $d$ changes but the coefficient matrix $C$ remains unchanged. 

The LU decomposition represents the coefficient matrix $C$ as $$C = PLU$$ where $P$ is a permutation matrix, $L$ is a lower triangular matrix with unit-diagonal and $U$ is an upper triangular matrix.

An initial time spent decomposing $C$ allows for rapid solution of similar systems of equations. 

To use LU decompositions:
1. Use the scipy.linalg.lu_factor() method on the coefficient matrix, and assign the result to a new variable.
2. Use the slin.lu_solve() function with the decomposition and the right-hand side vector as arguments.

In [ ]:
# coefficient matrix
C = np.array([[6, -2, 3], [2, -7, 5], [-3, 4, 0]])

# right-hand side vector
d = np.array([4, 0, -5])

# LU decomposition
lu = linalg.lu_factor(C)
sol = linalg.lu_solve(lu, d)
print sol # should be the same as the above sol from linalg.solve(C, d)

# change the right-hand side vector
sol = linalg.lu_solve(lu,[4, -3, 9])
print sol

## Applications in Economics

As soon as we know basic operations on a matrix and solving linear equations, we will be able to apply these knowledge to solve real-world problems in economics.

### Unemployment Rate

Unemployment rate changes over time as individuals gain or lose their employment. To describe the dynamics of unemployment rate, we consider the Markov model, which utilizes transitional probabilities.

In this model, we assume:

1. If an individual is unemployed in a given week, the probability for this individual to be employed on the following week is $p$, and $1 − p$ to stay unemployed.
2. If an individual is employed in a given week, the probability for this individual to stay employed on the following week is $q$, and $1 − q$ to be unemployed.

Let $x_t$ and $y_t$ be the ratio of individuals employed and unemployed in week $t$. Then the week-on-week changes are:

\begin{align}
x_{t+1} & = qx_t + py_t \\
y_{t+1} & = (1 − q)x_t + (1 − p)y_t
\end{align}

represented in matrix form:

$$v_{t+1} = Av_t$$

where transition matrix $A$ is

\begin{equation*}
A = 
\begin{bmatrix}
q & p \\
1-q & 1-p 
\end{bmatrix}
\end{equation*}

and state vector $v_t$ is

\begin{equation*}
v_t = 
\begin{bmatrix}
x_t \\
y_t
\end{bmatrix}
\end{equation*}

Now, the questions are:

* __Are there any steady states in this system?__
* __Can we reach the steady states?__

The state of the system after t weeks is given by:

\begin{align}
v_1 & = Av_0 \\
v_2 & = Av_1 = A(Av_0) = A^2v_0 \\
v_3 & = Av_2 = A(A^2v_0) = A^3v_0 \\
... \\
v_t & = A^tv_0
\end{align}

Suppose $p = 0.136$ and $q = 0.998$. If the unemployment rate is 5% at $t = 0$, then $x_0 = 0.95$ and $y_0 = 0.05$.

After $100$ weeks the state of the system would be

\begin{equation*}
\begin{bmatrix}
x_{100} \\
y_{100}
\end{bmatrix}
= 
\begin{bmatrix}
0.998 & 0.136 \\
0.002 & 0.864
\end{bmatrix}^{100}
\times
\begin{bmatrix}
0.95 \\
0.05
\end{bmatrix}
\end{equation*}

We can diagonize $A$ to compute $A^{100}$ efficiently by finding eigenvalues and eigenvectors:

$$A = PDP^{−1}$$

where $D$ is a diagonal matrix and $P$ is an invertible matrix. 

Thus, 

$$A^{100} = (PDP^{−1})^{100} = (PDP^{−1})(PDP^{−1})· · ·(PDP^{−1}) = PD^{100}P^{−1}$$

In [ ]:
# coefficient matrix
A = np.array([[0.998, 0.136], [0.002, 0.864]])

# original state
v0 = np.array([0.95, 0.05])

# find the eigenvalues and eigenvectors of the coefficient matrix
lamda, v = linalg.eig(A)

# diagonize the coefficient matrix
D = np.diag(lamda)
P = v
P_inverse = linalg.inv(P)

D_100 = D**100
A_100 = P.dot(D_100).dot(P_inverse)

v100 = A_100.dot(v0)
employed = v100[0]
unemployed = v100[1]
print employed
print unemployed

After 100 iterations, the system is in a state with employment rate = 98.6% and unemployment rate = 1.4%. 

Next, we will find the steady state, which means the unemployment and employment rate will not change. The system reaches steady state when 

\begin{equation*}
A
= 
\begin{bmatrix}
0.998 & 0.136 \\
0.002 & 0.864
\end{bmatrix}
\end{equation*}

and a state vector 
\begin{equation*}
v
= 
\begin{bmatrix}
x \\
y
\end{bmatrix}
\end{equation*} 

with $x, y ≥ 0$ and $x + y = 1$ such that $Av = v$.

In [ ]:
# coefficient matrix
A = np.array([[0.998, 0.136], [0.002, 0.864]])

# original state
v0 = np.array([0.95, 0.05])

# get eigenvalues and eigenvectors
lamda, v = linalg.eig(A)

# get diagonized matrix A = PDP^-1
D = np.diag(lamda)
P = v
P_inverse = sp.linalg.inv(P)

# the state of system in t iterations
vt = None
v_pre = v0

# count the iteration
i = 1

while True:
    # get the state of system in iteration i
    vt = P.dot(D**i).dot(P_inverse).dot(v0)
    
    # if the state of system no longer change, it reaches the steady state
    if (v_pre==vt).all():
        break
    v_pre = vt
    i += 1
    
employed = vt[0]
unemployed = vt[1]
print "After " + str(i) + " iterations, the system reaches steady state: " 
print employed
print unemployed

From the above calculation, we know that after 241 iterations, both employment and unemployment rate will no longer change and the system reaches a steady state.

We can visualize the process of change in unemployed and employed rate by plotting them with matplotlib.

In [ ]:
# ploting
import matplotlib.pyplot as plt

# coefficient matrix
A = np.array([[0.998, 0.136], [0.002, 0.864]])

# original state
v0 = np.array([0.95, 0.05])

#get eigenvalues and eigenvectors
lamda, v = linalg.eig(A)

#get diagonized matrix A = PDP^-1
D = np.diag(lamda)
P = v
P_inverse = sp.linalg.inv(P)

#the state of system in t iterations
vt = None
v_pre = v0

#count the iteration
i = 1

#lists for plotting
employed_list = []
unemployed_list = []
iteration_list = []

employed_list.append(v0[0])
unemployed_list.append(v0[1])
iteration_list.append(0)

while True:
    #get the state of system in iteration i
    vt = P.dot(D**i).dot(P_inverse).dot(v0)
    employed_list.append(vt[0])
    unemployed_list.append(vt[1])
    iteration_list.append(i)
    
    #if the state of system no longer change, it reaches the steady state
    if (v_pre==vt).all():
        break
    v_pre = vt
    i += 1

plt.scatter(iteration_list, employed_list, color = 'r')
plt.scatter(iteration_list, unemployed_list, color = 'b')
plt.show()

### Input-output Model

Leontief “input-output” Model is a classical model in economics.

The goal is to predict the proper level of production for each type of goods and services. The proper level of production should meet two requirements:

1. There should be enough goods to meet the demand.
2. There should be no "leftovers", i.e, unused goods.

Consider a simple economy that runs on 3 different types of output: 

1. Raw materials: Output from algriculture or mining
2. Services: Retailing, transportation, etc. 
3. Manufacturing: Artificial products like clothing and cars.

Now, the raw materials industry needs some of the output from the other two industries. For example, it requires manufactured machines to produce the materials and trucking to transport its goods. Also, it needs some of its own output to produce its own output, such as iron ore to make the steel for the rails that carry ore from the mines.

Similarly, each of the other two industries requires output from each other and itself. All of these requirements to produce $1 product can be summarized in a table:

|  Industry	    |   Raw Materials	|    Services	| Manufacturing |
|---------------|:-----------------:|:-------------:|:-------------:|
| Raw Materials |	    0.02	    |      0.04	    |     0.04      |
| Services	    |       0.05	    |      0.03	    |     0.01      |
| Manufacturing	|       0.2	        |      0.01	    |     0.1       |

For example, to provide \$1 service, the service sector requires \$0.05 raw materials, \$0.03 services, and \$0.01 manufactured goods.

The information can be shown by a "input-output" matrix:

\begin{equation*}
A = 
\begin{bmatrix}
0.02 & 0.04 & 0.04 \\
0.05 & 0.03 & 0.01 \\
0.2 & 0.01 & 0.1
\end{bmatrix}
\end{equation*}

The demand matrix shows how much (in billions) of each type of output is demanded:

\begin{equation*}
D = 
\begin{bmatrix}
400 \\
200 \\
600
\end{bmatrix}
\end{equation*}

For example, $200 billion services are demanded by consumers.

Finally, let $X$ denote the production matrix, a vector that represents the amount (in billions) produced by each of the industries. 

How to find the proper $X$?

The matrix product $AX$ represents the part of the production used internally by the industries themselves. 

Thus, the difference 

$$X - AX = (I-A)X$$ 

represents the output remains to satisfy the external demand. This demand will be exactly met with no leftover: 

$$(I-A)X = D$$ 

We can easily solve this equation for $X$ by SciPy.

In [ ]:
# input-output matrix
A = np.array([[0.02, 0.04, 0.04], [0.05, 0.03, 0.01], [0.2, 0.01, 0.1]])

# demand matrix
D = np.array([400, 200, 600])
I = np.eye(A.shape[0], M=A.shape[1])

# coefficient matrix
C = I - A

# production matrix
X = linalg.solve(C, D)
print X

Thereby we obtain the desired levels of production:

\begin{equation*}
X = 
\begin{bmatrix}
449.24 \\
237.27 \\
769.13
\end{bmatrix}
\end{equation*}

The raw materials should produce \$449.24 billion; the service should produce \$237.27 billion and the manufacturing should produce \$769.13 billion to reach "balance" economy.

We can also use LU expression to save time when we change the demand:

In [ ]:
# LU decomposition
lu = linalg.lu_factor(C)
X = linalg.lu_solve(lu, D) 
print X # should be the same as linalg.solve

# change demand matrix
D_ = np.array([300, 500, 100])
X = linalg.lu_solve(lu, D_)
print X

## Sparse Linear Algebra

When we have a large amount of data with lots of elements that are 0, we can use sparse matrix in Scipy to save space. 

To solve the sparse linear system, we can use scipy.sparse.linalg.spsolve()

In [ ]:
from scipy.sparse import *
from scipy.sparse import linalg as splinalg
from scipy import rand

# coefficient matrix
C = lil_matrix((2000, 2000))
C[0,:100] = rand(100)
C[1,100:200] = rand(100)
C.setdiag(rand(2000))

C = C.tocsr()

# vector
v = rand(2000)
X = splinalg.spsolve(C, v)
print X

We can also find the eigenvalues and eigenvectors of a sparse matrix by scipy.sparse.linalg.

For example, to find two smallest and two largest eigenvalues of coefficient matrix C:

In [ ]:
# find two smallest eigenvalues of cm
lamda_s, v_s = splinalg.eigs(C, 2, which="SM")
print lamda_s

# find two largest eigenvalues of cm
lamda_l, v_l = splinalg.eigs(C, 2, which="LM")
print lamda_l

## Summary and Reference

Linear algebra is widely used from social science to engineering. However, for "big data", we can hardly solve it without powerful computing methodologies. Thanks to SciPy, we can easily deal with linear algebra by Python.

1. Installing the SciPy Stack: https://www.scipy.org/install.html#individual-packages
2. Installing the SciPy with pip: http://stackoverflow.com/questions/2213551/installing-scipy-with-pip    
3. Scientific Programming, Analysis and Visualization with Python: 
   http://snowball.millersville.edu/~adecaria/ESCI386P/esci386-lesson18-Linear-Algebra.pdf
4. Numpy Matrix and Linear Algebra: http://www.bogotobogo.com/python/python_numpy_matrix_tutorial.php
5. scipy.linalg: http://docs.scipy.org/doc/scipy/reference/tutorial/linalg.html
6. Invertible Matrix: https://en.wikipedia.org/wiki/Invertible_matrix
7. Transpose: https://en.wikipedia.org/wiki/Transpose
8. Determinant: https://en.wikipedia.org/wiki/Determinant
9. Trace: https://en.wikipedia.org/wiki/Trace_(linear_algebra)
10. Eigenvalues and Eigenvectors: https://en.wikipedia.org/wiki/Eigenvalues_and_eigenvectors
11. Eigenvalues and Eigenvectors: http://www.dr-eriksen.no/teaching/GRA6035/2010/lecture3-hand.pdf
12. The Leontief Input-Output Model: http://barnyard.syr.edu/mat183/l32/
13. Sam's Scientific Python Tools: http://www.sam.math.ethz.ch/~raoulb/teaching/PythonTutorial/intro_scipy.html